### PR TITLE
Clarify the oidc-agent workflow need for two browser accesses

### PR DESCRIPTION
**Pull request by DrDaveD**
See discussion in #3.  @msalle @marcvs please comment.

I deleted "OP" because I don't know what that stands for.

### CODE REVIEW

**Comment by marcvs** [comment]
"OP" stands for OpenID Connect Provider.

I can live with the changes made.

A really minor thing; in l77 it says "Script" ... obtains the RT.  It is the oidc-agent that does that, but I'm not sure this matters.

**Comment by DrDaveD** [comment]
Good point.  In fact it was all a bit muddled.  I tried to redo it to make it more technically accurate.  Please review again to see if I did it right.

**Comment by DrDaveD** [comment]
@msalle Please re-review

**Review by msalle — COMMENTED** [review]
Hi, it now looks fine to me, but it is probably good to also get a review from @marcvs or @zachmann since they know the flows much better.

**Comment by marcvs** [comment]
Looks much better to me. Thanks Dave for the edit!!

**Comment by DrDaveD** [comment]
@hannahshort Can you please merge this?

**Pull request merged**
